### ISSUE TITLE
Can't bind to 'leafletMarkerCluster' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by maxberg1c** [Asymmetrik/ngx-leaflet-markercluster#11]
I'm using ngx-leaflet-markercluster in an angular 5 application. I changed my code according to the demo but still getting the following error:

> Can't bind to 'leafletMarkerCluster' since it isn't a known property of 'div'.

**Comment by reblace** [comment]
Make sure you're importing the ```LeafletMarkerclusterModule``` into the appropriate module of your application (similar to what you do with the ngx-leaflet module). The error you're getting is usually caused by the module not being imported, so Angular doesn't know about the directives.

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { LeafletModule } from '@asymmetrik/ngx-leaflet';
import { LeafletMarkerClusterModule } from '@asymmetrik/ngx-leaflet-markercluster';

@NgModule({
	imports: [
		CommonModule,
		FormsModule,

		LeafletModule.forRoot(),
		LeafletMarkerClusterModule.forRoot()
	],
	declarations: [
		MyComponent
	],
	exports: [
		MyComponent
	],
	bootstrap: [ MyComponent ],
	providers: [ ]
})
export class MyModule { }
```

I'm surprised I don't have this in the README, so I'll make a note to fix that.

**Comment by reblace** [comment]
Answered on StackOverflow
